name: Build TWA APK

on:
  push:
    branches:
      - main  # Trigger when you push to the "main" branch

jobs:
  build:
    runs-on: ubuntu-latest  # Build the project on Ubuntu

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (required for Bubblewrap)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Set up Node.js version 16

      # Step 3: Install Bubblewrap CLI globally
      - name: Install Bubblewrap CLI
        run: |
          npm install -g @bubblewrap/cli

      # Step 4: Initialize TWA Project using your PWA's manifest.json
      - name: Initialize TWA
        run: |
          bubblewrap init --manifest https://eojte.github.io/Pwa/manifest.json

      # Step 5: Build the TWA APK
      - name: Build TWA APK
        run: |
          bubblewrap build

      # Step 6: List files in the output directory to verify the APK is there
      - name: List files in output directory
        run: ls -la ./output  # Make sure the APK is in the output folder

      # Step 7: Upload APK as an artifact
      - name: Upload APK as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: twa-apk
          path: ./output/app-release.apk  # Ensure this is the correct path to your APK
